# Generated by Django 5.1.1 on 2024-12-04 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('oracle_text', models.CharField(max_length=500)),
                ('power', models.IntegerField(blank=True)),
                ('toughness', models.IntegerField(blank=True)),
                ('mana_cost', models.CharField(blank=True, max_length=20)),
                ('color_identity', models.IntegerField()),
                ('converted_mana_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('oracle_text', models.CharField(max_length=500)),
                ('cards', models.ManyToManyField(to='card_browse.card')),
            ],
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_browse.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_browse.user')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('user_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_browse.usercard')),
            ],
        ),
    ]
