# Generated by Django 5.1.1 on 2024-12-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_browse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='mana_cost',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='toughness',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
