# Generated by Django 5.1.1 on 2025-01-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_browse', '0003_historicaloffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('COMMON', 'Common'), ('UNCOMMON', 'Uncommon'), ('RARE', 'Rare'), ('MYTHIC_RARE', 'Mythic Rare')], default='COMMON', max_length=30),
        ),
    ]
