# Generated by Django 5.1.1 on 2025-01-19 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_browse', '0004_card_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloffer',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offer',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='cards',
            field=models.ManyToManyField(related_name='Keywords', to='card_browse.card'),
        ),
    ]
