# Generated by Django 5.1.1 on 2025-01-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_browse', '0005_historicaloffer_published_offer_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloffer',
            name='id',
            field=models.IntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
