# Generated by Django 5.1.1 on 2025-01-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_browse', '0007_remove_keyword_cards_keywords_on_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='cards',
            field=models.ManyToManyField(related_name='Keywords', through='card_browse.Keywords_On_Cards', to='card_browse.card'),
        ),
    ]
