# Generated by Django 5.1.1 on 2025-01-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_browse', '0008_keyword_cards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaloffer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Offer', 'verbose_name_plural': 'historical Offers'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Offer', 'verbose_name_plural': 'Offers'},
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
