# Generated by Django 5.1.1 on 2025-01-19 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_browse', '0009_alter_historicaloffer_options_alter_offer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='cards',
        ),
    ]
