# Generated by Django 5.1.1 on 2025-01-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_browse', '0010_remove_keyword_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='keywords',
            field=models.ManyToManyField(related_name='cards', through='card_browse.Keywords_On_Cards', to='card_browse.keyword'),
        ),
    ]
