# Generated by Django 5.1.1 on 2025-01-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_browse', '0011_card_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cards',
            field=models.ManyToManyField(related_name='users', to='card_browse.card'),
        ),
    ]
