# Generated by Django 5.1.1 on 2025-01-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_browse', '0012_user_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cards',
        ),
    ]
