# Generated by Django 5.1.1 on 2025-01-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_browse', '0014_alter_keywords_on_cards_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='oracle_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
